version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            - pip install --upgrade pip
            # Install dependencies needed for running the static analysis
            - sudo yum install mysql-devel -y
            - sudo yum install gcc -y
            - pip install -r requirements.txt
    pre_build:
        commands:
            - python --version
artifacts:
    files:
        - '**/*'
