# Generated by Django 2.1.5 on 2023-04-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacations',
            name='ticket',
            field=models.CharField(default=2345, max_length=255),
            preserve_default=False,
        ),
    ]
